name : Postman Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron : 30 02 * * * # 8 am IST Every day
    - cron : 00 14 * * * # 730 pm IST Every day
    - cron : 00 06 * * 1-5 # 1130 am IST Every Monday to Friday

jobs:
  run-postman-tests:
    runs-on: ubuntu-least

    steps:
      - name: Checkout the code
        uses: actions/checkout@v5.0.0
  
      - name: Install Nodejs and npm
        uses: actions/setup-node@v5.0.0
        with:
          node-version: '22'
          
      - name: Install Newman and Html-extra globally
        run: |
             npm install -g newman
             npm install -g newman-reporter-htmlextra

      - name: Run Postman Collection with newman
        run: |
             newman run 'Inwarranty-flow Collection.postman_collection.json' \
             -e QA.postman_environment.json \
             -d testData.csv \
             -r Cli,htmlextra

      - name: Newman Report
        if: always() # ensure that the archive executed irrecspective whether the previous step has passed or not!
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Newman Report
          path: newman/*.html

      - name: Create github page branch
        if: always()
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: newman/
        
      
